CREATE OR REPLACE FUNCTION CARD_BACK.F_GET_USER_ID (V_USER_NAME VARCHAR2)
   RETURN INTEGER 
   IS 
   S_USER VARCHAR2(100);
   X INTEGER;
BEGIN /* Функция вернёт ID пользователя   (из таблицы XMASTER.XCARD_USER)  */
   
   S_USER := TRIM(V_USER_NAME);
   
   SELECT USER_ID INTO X FROM XMASTER.XCARD_USER WHERE UPPER(USERNAME)=UPPER(S_USER);
   
   RETURN( NVL(X,-1) );
   
EXCEPTION 
    WHEN OTHERS THEN 
           RETURN(-1);
     
END;
/