CREATE OR REPLACE FUNCTION F_GET_CURRENT_SESSION_INFO
   RETURN VARCHAR2 
   IS 
   S_USER VARCHAR2(200);

BEGIN
   
   SELECT SYS_CONTEXT ('USERENV', 'SESSION_USER') || ' ' || SYS_CONTEXT('USERENV', 'SESSIONID') INTO S_USER FROM DUAL;
   RETURN (S_USER);

EXCEPTION 
    WHEN OTHERS THEN 
           RETURN('');
     
END;
