
CREATE OR REPLACE FUNCTION F_GET_PIN_CHECK_STATUS( I_ICC IN INTEGER, I_XCST_ID IN INTEGER )
RETURN VARCHAR2 
IS

F VARCHAR2(12);  
 
BEGIN
   
SELECT PIN INTO F FROM XMASTER.XCARD WHERE ICC = LPAD(I_ICC,10,'0') AND XCST_XCST_ID = I_XCST_ID;

RETURN (F);

EXCEPTION 
    WHEN OTHERS THEN 
           RETURN('0');
     
END;
