CREATE OR REPLACE FUNCTION CARD_BACK.F_GET_USER_NAME(I_ID_USER IN INTEGER)
   RETURN VARCHAR2 
   IS 
   S_USER VARCHAR2(200);
BEGIN
     
   SELECT DEF INTO S_USER FROM XMASTER.XCARD_USER WHERE USER_ID=I_ID_USER ;
   
   RETURN( NVL(S_USER,'?') );
   
EXCEPTION 
    WHEN OTHERS THEN 
           RETURN('?');
     
END;