CREATE OR REPLACE FUNCTION F_GET_CURRENT_USER_ID
   RETURN NUMBER 
   IS 
   S_USER VARCHAR2(200);
   X INTEGER;
BEGIN /* Функция вернёт ID (из таблицы XMASTER.XCARD_USER) текущего пользователя  */
   
   SELECT SYS_CONTEXT ('USERENV', 'SESSION_USER') INTO S_USER FROM DUAL;
   
   SELECT USER_ID INTO X FROM XMASTER.XCARD_USER WHERE UPPER(USERNAME)=UPPER(S_USER);
   
   RETURN( NVL(X,-1) );
   
EXCEPTION 
    WHEN OTHERS THEN 
           RETURN(-1);
     
END;
