CREATE OR REPLACE VIEW V_ACTIVE_RANGE as ---- Диапазоны заявок, которые не были отменены ----
SELECT A.* FROM
T_RETURN_RANGE A
INNER JOIN T_RETURN B
    ON A.ID_RETURN = B.ID_RETURN
        WHERE  B.ID_STATUS NOT IN (SELECT ID_STATUS FROM T_RETURN_STATUS WHERE UPPER(CODE)='CANCELED')
ORDER BY A.ID_RETURN, A.RANGE_MIN


