CREATE OR REPLACE VIEW V_ACTIVATION
AS
/* Выборка Заявок и подсчёт числа активированных карт */
SELECT B.*, A.COUNT_ACTIVATED FROM
    (
    SELECT 
    ID_ACTIVATION, 
    COUNT(*) as COUNT_ACTIVATED
    FROM TA_CARD 
    WHERE R_CODE='0'
    GROUP BY ID_ACTIVATION
    ) A
INNER JOIN
    TA_ACTIVATION B
    ON A.ID_ACTIVATION = B.ID_ACTIVATION
ORDER BY B.ID_RETURN, B.ID_ACTIVATION    
    
