CREATE OR REPLACE VIEW V_RETURN_BALANCE AS
/*  Вычислим сумму денежных средств по каждой Заявке на возврат  */
SELECT ID_RETURN, SUM( (1+RANGE_MAX - RANGE_MIN) * F_BALANCE ) as F_AMOUNT FROM T_RETURN_RANGE
GROUP BY ID_RETURN
ORDER BY ID_RETURN
