CREATE OR REPLACE VIEW V_WATCH_ACTIVATION as
SELECT A.ID_RETURN, A.MSISDN,  R_CODE, R_MESSAGE, MIN(A.START_DATE) as MIN_START_DATE, COUNT(*) as C_COUNT from 
TA_ACTIVATION A
INNER JOIN 
TA_CARD B
ON A.ID_ACTIVATION=B.ID_ACTIVATION
GROUP BY A.ID_RETURN, A.MSISDN,  R_CODE, R_MESSAGE
ORDER BY 1, 2
